# To collect data there is a SCHDULE to follow, and a Data Logger program

The schdule is for telling me when to do what task, and the data logger is a program that is used to report when I exactly did the task.

Each mineral stimuli needs to be worn in periods of 4 hours, in between periods of control
[stimuli, control 1, stimuli, control 2]

In [1]:
import numpy as np

In [36]:
start_hour = 9  
end_hour = 24  # do not want it to go past this value, but don't care if the last value is 20
interval = 4  #interval

out1 = np.array(range(start_hour, end_hour, interval))
print('out1 : ' + str(out1))

days = 30
mat = np.zeros((days, 13))
for i in range(days):
    stim1 = np.random.permutation(2)  # [0=rose quartz, 1=howlite]
    ctrl1 = np.random.permutation(2)  # [0=no bracelet, 1=normal metal bracelet]
    stim2 = np.random.permutation(2)
    ctrl2 = np.random.permutation(2)
    mat[i,:] = [i+1, stim1[0], out1[0], out1[1], ctrl1[0], out1[1], out1[2], stim2[0], out1[2], out1[3], ctrl2[0], out1[3], end_hour]
print(mat)

out1 : [ 9 13 17 21]
[[ 1.  0.  9. 13.  1. 13. 17.  1. 17. 21.  0. 21. 24.]
 [ 2.  0.  9. 13.  1. 13. 17.  0. 17. 21.  1. 21. 24.]
 [ 3.  0.  9. 13.  1. 13. 17.  0. 17. 21.  0. 21. 24.]
 [ 4.  1.  9. 13.  0. 13. 17.  0. 17. 21.  1. 21. 24.]
 [ 5.  1.  9. 13.  1. 13. 17.  1. 17. 21.  1. 21. 24.]
 [ 6.  1.  9. 13.  1. 13. 17.  0. 17. 21.  1. 21. 24.]
 [ 7.  1.  9. 13.  1. 13. 17.  0. 17. 21.  0. 21. 24.]
 [ 8.  0.  9. 13.  1. 13. 17.  1. 17. 21.  1. 21. 24.]
 [ 9.  1.  9. 13.  0. 13. 17.  1. 17. 21.  0. 21. 24.]
 [10.  0.  9. 13.  0. 13. 17.  1. 17. 21.  1. 21. 24.]
 [11.  0.  9. 13.  0. 13. 17.  1. 17. 21.  0. 21. 24.]
 [12.  0.  9. 13.  0. 13. 17.  1. 17. 21.  1. 21. 24.]
 [13.  1.  9. 13.  1. 13. 17.  0. 17. 21.  1. 21. 24.]
 [14.  0.  9. 13.  0. 13. 17.  0. 17. 21.  1. 21. 24.]
 [15.  0.  9. 13.  0. 13. 17.  0. 17. 21.  1. 21. 24.]
 [16.  0.  9. 13.  1. 13. 17.  0. 17. 21.  1. 21. 24.]
 [17.  1.  9. 13.  0. 13. 17.  0. 17. 21.  0. 21. 24.]
 [18.  1.  9. 13.  1. 13. 17.  1. 17. 21.  0

In [41]:
np.savetxt("schedule_30days_juin.txt", np.array(mat), fmt="%s")

# Data Logger program

In [ ]:
# Created datalogger_gui.py to conveniently log the event data

In [ ]:
# Convert the .py file to a .exe file, so it is easier to access - DID NOT WORK
# There are less files using the --onefile option 
"C:\Users\HP EliteBook\AppData\Roaming\Python\Python39\Scripts\pyinstaller.exe" --onefile datalogger_gui.py
# a .exe file is created in the FullPathOfFile\dist

# Temperature Logger
https://create.arduino.cc/projecthub/yanvaf/arduino-and-tmp102-temperature-sensor-11bd94


# Estimating breathing from HR